### ISSUE TITLE
Everything outdated

### ISSUE THREAD

**Issue by OverLordGoldDragon** [inducer/pycuda#269]
Are there plans on compatibility with newer versions of Python, CUDA, and the rest? Almost all requirements date over a decade back, and I've tried installing for hours but got nowhere. It'd help if maintainers made install instructions clearer or made a working `pip` / `conda` install. At this point I've given up but can provide further info if it helps.

Thanks

**Comment by inducer** [comment]
Thanks for your note. PyCUDA should be compatible with all the latest things, while maintaining compatibility with the (as you put it) decade-old stuff. In that sense, those minimum requirements should still be accurate. It gets built in CI against more or less the latest code (Py3.9, CUDA 11.x) roughly every week, without any problems: https://gitlab.tiker.net/inducer/pycuda/-/pipelines

So if you're having problems, incompatibilities with recent version should not be the root cause.

**Comment by OverLordGoldDragon** [comment]
Suppose I'm unlucky, regardless instructions could be bit clearer; I've had less trouble with my first-ever TensorFlow building from source. Closing as my problem's solved, went with Cupy.
