### ISSUE TITLE
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid value

### ISSUE THREAD

**Issue by aditya4d** [inducer/pycuda#46]
Hi,
I am trying to use async memcpy using pycuda. I am getting this error:

``` shell
Traceback (most recent call last):
  File "streams.py", line 29, in <module>
    drv.memcpy_htod_async(a_gpu,a_pin)
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid value
```

The source code is:

``` python
import numpy as np
import pycuda.autoinit
import pycuda.driver as drv

from pycuda.compiler import SourceModule

mod = SourceModule("""
__global__ void add_them(long *dest, long *a, long *b){
int tx = blockIdx.x;
dest[tx] = a[tx] + b[tx];
}
""")

add_them = mod.get_function("add_them")

a = np.random.randint(10, size = 65536)
b = np.random.randint(10, size = 65536)

dest = np.zeros_like(a)
a_gpu = drv.mem_alloc(a.nbytes)
b_gpu = drv.mem_alloc(b.nbytes)
dest_gpu = drv.mem_alloc(dest.nbytes)

a_pin = drv.register_host_memory(a)
b_pin = drv.register_host_memory(b)

drv.memcpy_htod_async(a_gpu,a_pin)
drv.memcpy_htod_async(b_gpu,b_pin)

add_them(dest_gpu,a_gpu,b_gpu,block=(1,1,1),grid=(65536,1,1))

drv.memcpy_dtoh(dest,dest_gpu)
```

**Comment by sjperkins** [comment]
@inducer I am running into the same error on CUDA 7.0.0.

The python script above reproduces the problem for me. However, the C code runs successfully.

**Comment by inducer** [comment]
I don't think the script above is valid. I'm on driver 352.21, and the relevant PyCUDA test passes (but the script fails):

python test_driver.py 'TestDriver().test_register_host_memory()'

**Comment by sjperkins** [comment]
@inducer The test case succeeds, but only tests a successful call to pycuda.driver.register_host_memory. If one extends the test case as follows:

```python
a = drv.aligned_empty((2**20,), np.float64, alignment=4096)
a_pin = drv.register_host_memory(a)

gpu_ary = drv.mem_alloc_like(a)
stream = drv.Stream()
drv.memcpy_htod_async(gpu_ary, a_pin, stream)
```

it fails with the error reported in this issue.

**Comment by sjperkins** [comment]
Making my previous comment more precise, it in fact fails with

pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid **argument**

**Comment by sjperkins** [comment]
@inducer I've created two versions of this behaviour:

- [CUDA C](https://gist.github.com/sjperkins/8cd836604ff7d2a2a3b3)
- [PyCUDA](https://gist.github.com/sjperkins/d9e6db1b2d6038febb72)

The CUDA C version seems to run fine for me, but if `pycuda.driver.register_host_memory` is used, the PyCUDA versions fails with:

pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: **invalid argument**

 If `pycuda.driver.pagelocked_empty` is used to create pinned memory instead, the PyCUDA version succeeds.

Is it possible that the `wrap_cudadrv.cpp` is returning an invalid `HostPointer` from `register_host_memory`? It's the only I thing I can think of. It's unlikely because within the test case, I've got a `assert np.all(a == a_pin)`. 

I am aware of these use cases where the pinned host memory is mapped into the device's address space, and the address of this space is retrieved with `get_device_pointer()`. See this snippet from @fasiha's (failing) [gist](https://gist.github.com/fasiha/4036693) for e.g.

```python
# Time use of pinned host memory:
x = drv.aligned_empty((N, N), dtype=np.float64, order='C')
x = drv.register_host_memory(x, flags=drv.mem_host_register_flags.DEVICEMAP)
x_gpu_ptr = np.intp(x.base.get_device_pointer())
```

But I don't think this is the default behaviour. As illustrated by the CUDA C version, it should be possible to just pin the host memory without performing a corresponding mapped allocation on the device, and then just use the host pointer as a call to the asynchronous memory copy.

**Comment by inducer** [comment]
As @sjperkins correctly pointed out in #82, there was a bug here, resolved by that PR.
